a: b
sprint:
  application:
    name: todoapp

  datasource:
    url: jdbc:postgres://0.0.0.0:5432/postgres
    username: mluser
    password: mluser
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 3
      connection-timeout: 30000
    driver-class-name: org.postgresql.Driver
  analyticsuser:
    url: jdbc:postgres://0.0.0.0:5432/postgres
    username: analyticsuser
    password: analyticsuser
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 3
      connection-timeout: 30000
    driver-class-name: org.postgresql.Driver

  # cloud:
  #   config:
  #     importCheck:
  #       enabled: false
      