a: b
spring:
  application:
    name: todoapp
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: mluser
    password: mluser
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 30
      connection-timeout: 30000
    driver-class-name: org.postgresql.Driver
analyticsuser:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: analyticsuser
    password: analyticsuser
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 30
      connection-timeout: 30000
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          fetch_size: 4000
        order_inserts: true
        order_updates: true
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

server:
  port: 8080
  servlet:
    context-path: /todo
  compression:
    enabled: true
    mime-types: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,application/json
    min-response-size: 1024

logging:
  level:
    org.springframework.boot.env: DEBUG

  # cloud:
  #   config:
  #     importCheck:
  #       enabled: false
      